/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MappingRecord = IDL.Record({
  'karigarName' : IDL.Text,
  'excelGenericName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Ready' : IDL.Null,
  'Hallmark' : IDL.Null,
  'ReturnFromHallmark' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderType = IDL.Variant({
  'CO' : IDL.Null,
  'RB' : IDL.Null,
  'SO' : IDL.Null,
});
export const Time = IDL.Int;
export const AppRole = IDL.Variant({
  'Staff' : IDL.Null,
  'Admin' : IDL.Null,
  'Karigar' : IDL.Null,
});
export const MasterDesignMapping = IDL.Record({
  'karigar' : IDL.Text,
  'excelGenericName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const OrderStatusLog = IDL.Record({
  'id' : IDL.Text,
  'oldStatus' : OrderStatus,
  'orderId' : IDL.Text,
  'updatedAt' : Time,
  'updatedBy' : IDL.Text,
  'newStatus' : OrderStatus,
});
export const Order = IDL.Record({
  'weight' : IDL.Float64,
  'status' : OrderStatus,
  'readyDate' : IDL.Opt(Time),
  'originalOrderId' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'movedBy' : IDL.Opt(IDL.Text),
  'size' : IDL.Float64,
  'orderDate' : IDL.Opt(Time),
  'orderType' : OrderType,
  'design' : IDL.Text,
  'orderId' : IDL.Text,
  'orderNo' : IDL.Text,
  'karigarName' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'updatedBy' : IDL.Opt(IDL.Text),
  'genericName' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'lastAction' : IDL.Opt(IDL.Text),
  'remarks' : IDL.Text,
  'product' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DesignMapping = IDL.Record({
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'karigarName' : IDL.Text,
  'updatedAt' : Time,
  'updatedBy' : IDL.Opt(IDL.Text),
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const Karigar = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
});
export const AppStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const AppUser = IDL.Record({
  'id' : IDL.Text,
  'status' : AppStatus,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : AppRole,
  'karigarName' : IDL.Opt(IDL.Text),
  'loginId' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const MasterDataRow = IDL.Record({
  'karigar' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const MasterReconciliationResult = IDL.Record({
  'missingInExcel' : IDL.Vec(MasterDataRow),
  'matchedRows' : IDL.Vec(MasterDataRow),
  'missingInSystem' : IDL.Vec(MasterDataRow),
});
export const MasterPersistedResponse = IDL.Record({
  'reconciliationResult' : MasterReconciliationResult,
  'persistedRows' : IDL.Vec(MasterDataRow),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'batchSaveDesignMappings' : IDL.Func(
      [IDL.Vec(MappingRecord), IDL.Text],
      [],
      [],
    ),
  'batchUpdateOrderStatus' : IDL.Func(
      [IDL.Vec(IDL.Text), OrderStatus, IDL.Text],
      [],
      [],
    ),
  'clearAllDesignMappings' : IDL.Func([], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        OrderType,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createOrderWithDate' : IDL.Func(
      [
        IDL.Text,
        OrderType,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
      ],
      [IDL.Text],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AppRole, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'getAllMasterDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(MasterDesignMapping)],
      ['query'],
    ),
  'getAllOrderStatusLogs' : IDL.Func([], [IDL.Vec(OrderStatusLog)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getDesignCountByKarigar' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getDesignImageMapping' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
      ['query'],
    ),
  'getDesignMapping' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DesignMapping)],
      ['query'],
    ),
  'getFilteredOutKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
  'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMasterDesigns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrderStatusLog' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderStatusLog)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getReadyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUniqueKarigarsFromDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getUserByLoginId' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'initDefaultAdmin' : IDL.Func([], [], []),
  'isExistingDesignCodes' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'logOrderStatusChange' : IDL.Func(
      [IDL.Text, OrderStatus, OrderStatus, IDL.Text],
      [],
      [],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'id' : IDL.Text,
            'name' : IDL.Text,
            'role' : AppRole,
            'karigarName' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'markOrdersAsPending' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
  'markOrdersAsReady' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
  'persistMasterDataRows' : IDL.Func(
      [IDL.Vec(MasterDataRow)],
      [MasterPersistedResponse],
      [],
    ),
  'reconcileMasterFile' : IDL.Func([], [MasterReconciliationResult], ['query']),
  'registerKarigar' : IDL.Func([IDL.Text], [], []),
  'resetActiveOrders' : IDL.Func([], [], []),
  'resetDefaultAdmin' : IDL.Func([], [], []),
  'resetUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDesignMapping' : IDL.Func([DesignMapping], [], []),
  'supplyAndReturnOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'supplyOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateMasterDesignKarigars' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AppRole, IDL.Opt(IDL.Text), AppStatus],
      [],
      [],
    ),
  'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MappingRecord = IDL.Record({
    'karigarName' : IDL.Text,
    'excelGenericName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Ready' : IDL.Null,
    'Hallmark' : IDL.Null,
    'ReturnFromHallmark' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderType = IDL.Variant({
    'CO' : IDL.Null,
    'RB' : IDL.Null,
    'SO' : IDL.Null,
  });
  const Time = IDL.Int;
  const AppRole = IDL.Variant({
    'Staff' : IDL.Null,
    'Admin' : IDL.Null,
    'Karigar' : IDL.Null,
  });
  const MasterDesignMapping = IDL.Record({
    'karigar' : IDL.Text,
    'excelGenericName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const OrderStatusLog = IDL.Record({
    'id' : IDL.Text,
    'oldStatus' : OrderStatus,
    'orderId' : IDL.Text,
    'updatedAt' : Time,
    'updatedBy' : IDL.Text,
    'newStatus' : OrderStatus,
  });
  const Order = IDL.Record({
    'weight' : IDL.Float64,
    'status' : OrderStatus,
    'readyDate' : IDL.Opt(Time),
    'originalOrderId' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'movedBy' : IDL.Opt(IDL.Text),
    'size' : IDL.Float64,
    'orderDate' : IDL.Opt(Time),
    'orderType' : OrderType,
    'design' : IDL.Text,
    'orderId' : IDL.Text,
    'orderNo' : IDL.Text,
    'karigarName' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'updatedBy' : IDL.Opt(IDL.Text),
    'genericName' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'lastAction' : IDL.Opt(IDL.Text),
    'remarks' : IDL.Text,
    'product' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DesignMapping = IDL.Record({
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'karigarName' : IDL.Text,
    'updatedAt' : Time,
    'updatedBy' : IDL.Opt(IDL.Text),
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const Karigar = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
  });
  const AppStatus = IDL.Variant({ 'Inactive' : IDL.Null, 'Active' : IDL.Null });
  const AppUser = IDL.Record({
    'id' : IDL.Text,
    'status' : AppStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : AppRole,
    'karigarName' : IDL.Opt(IDL.Text),
    'loginId' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const MasterDataRow = IDL.Record({
    'karigar' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const MasterReconciliationResult = IDL.Record({
    'missingInExcel' : IDL.Vec(MasterDataRow),
    'matchedRows' : IDL.Vec(MasterDataRow),
    'missingInSystem' : IDL.Vec(MasterDataRow),
  });
  const MasterPersistedResponse = IDL.Record({
    'reconciliationResult' : MasterReconciliationResult,
    'persistedRows' : IDL.Vec(MasterDataRow),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'batchSaveDesignMappings' : IDL.Func(
        [IDL.Vec(MappingRecord), IDL.Text],
        [],
        [],
      ),
    'batchUpdateOrderStatus' : IDL.Func(
        [IDL.Vec(IDL.Text), OrderStatus, IDL.Text],
        [],
        [],
      ),
    'clearAllDesignMappings' : IDL.Func([], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          OrderType,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createOrderWithDate' : IDL.Func(
        [
          IDL.Text,
          OrderType,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
        ],
        [IDL.Text],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AppRole, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'getAllMasterDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(MasterDesignMapping)],
        ['query'],
      ),
    'getAllOrderStatusLogs' : IDL.Func(
        [],
        [IDL.Vec(OrderStatusLog)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getDesignCountByKarigar' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getDesignImageMapping' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
        ['query'],
      ),
    'getDesignMapping' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DesignMapping)],
        ['query'],
      ),
    'getFilteredOutKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
    'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMasterDesigns' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrderStatusLog' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderStatusLog)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getReadyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUniqueKarigarsFromDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getUserByLoginId' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'initDefaultAdmin' : IDL.Func([], [], []),
    'isExistingDesignCodes' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'logOrderStatusChange' : IDL.Func(
        [IDL.Text, OrderStatus, OrderStatus, IDL.Text],
        [],
        [],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'id' : IDL.Text,
              'name' : IDL.Text,
              'role' : AppRole,
              'karigarName' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'markOrdersAsPending' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
    'markOrdersAsReady' : IDL.Func([IDL.Vec(IDL.Text), IDL.Text], [], []),
    'persistMasterDataRows' : IDL.Func(
        [IDL.Vec(MasterDataRow)],
        [MasterPersistedResponse],
        [],
      ),
    'reconcileMasterFile' : IDL.Func(
        [],
        [MasterReconciliationResult],
        ['query'],
      ),
    'registerKarigar' : IDL.Func([IDL.Text], [], []),
    'resetActiveOrders' : IDL.Func([], [], []),
    'resetDefaultAdmin' : IDL.Func([], [], []),
    'resetUserPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDesignMapping' : IDL.Func([DesignMapping], [], []),
    'supplyAndReturnOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'supplyOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateMasterDesignKarigars' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AppRole, IDL.Opt(IDL.Text), AppStatus],
        [],
        [],
      ),
    'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };