/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Staff' : null } |
  { 'Admin' : null } |
  { 'Karigar' : null };
export type AppStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface AppUser {
  'id' : string,
  'status' : AppStatus,
  'name' : string,
  'createdAt' : Time,
  'role' : AppRole,
  'karigarName' : [] | [string],
  'loginId' : string,
  'passwordHash' : string,
}
export interface DesignMapping {
  'createdAt' : Time,
  'createdBy' : string,
  'karigarName' : string,
  'updatedAt' : Time,
  'updatedBy' : [] | [string],
  'genericName' : string,
  'designCode' : string,
}
export type ExternalBlob = Uint8Array;
export interface Karigar {
  'name' : string,
  'createdAt' : Time,
  'createdBy' : string,
}
export interface MappingRecord {
  'karigarName' : string,
  'excelGenericName' : string,
  'genericName' : string,
  'designCode' : string,
}
export interface MasterDataRow {
  'karigar' : string,
  'genericName' : string,
  'designCode' : string,
}
export interface MasterDesignMapping {
  'karigar' : string,
  'excelGenericName' : string,
  'genericName' : string,
  'designCode' : string,
}
export interface MasterPersistedResponse {
  'reconciliationResult' : MasterReconciliationResult,
  'persistedRows' : Array<MasterDataRow>,
}
export interface MasterReconciliationResult {
  'missingInExcel' : Array<MasterDataRow>,
  'matchedRows' : Array<MasterDataRow>,
  'missingInSystem' : Array<MasterDataRow>,
}
export interface Order {
  'weight' : number,
  'status' : OrderStatus,
  'readyDate' : [] | [Time],
  'originalOrderId' : [] | [string],
  'createdAt' : Time,
  'movedBy' : [] | [string],
  'size' : number,
  'orderDate' : [] | [Time],
  'orderType' : OrderType,
  'design' : string,
  'orderId' : string,
  'orderNo' : string,
  'karigarName' : [] | [string],
  'updatedAt' : Time,
  'updatedBy' : [] | [string],
  'genericName' : [] | [string],
  'quantity' : bigint,
  'lastAction' : [] | [string],
  'remarks' : string,
  'product' : string,
}
export type OrderStatus = { 'Ready' : null } |
  { 'Hallmark' : null } |
  { 'ReturnFromHallmark' : null } |
  { 'Pending' : null };
export interface OrderStatusLog {
  'id' : string,
  'oldStatus' : OrderStatus,
  'orderId' : string,
  'updatedAt' : Time,
  'updatedBy' : string,
  'newStatus' : OrderStatus,
}
export type OrderType = { 'CO' : null } |
  { 'RB' : null } |
  { 'SO' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'batchSaveDesignMappings' : ActorMethod<
    [Array<MappingRecord>, string],
    undefined
  >,
  'batchUpdateOrderStatus' : ActorMethod<
    [Array<string>, OrderStatus, string],
    undefined
  >,
  'clearAllDesignMappings' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<
    [
      string,
      OrderType,
      string,
      string,
      number,
      number,
      bigint,
      string,
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'createOrderWithDate' : ActorMethod<
    [
      string,
      OrderType,
      string,
      string,
      number,
      number,
      bigint,
      string,
      [] | [string],
      [] | [string],
      [] | [Time],
    ],
    string
  >,
  'createUser' : ActorMethod<
    [string, string, string, AppRole, [] | [string]],
    string
  >,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'getAllMasterDesignMappings' : ActorMethod<[], Array<MasterDesignMapping>>,
  'getAllOrderStatusLogs' : ActorMethod<[], Array<OrderStatusLog>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getDesignCountByKarigar' : ActorMethod<[], Array<[string, bigint]>>,
  'getDesignImageMapping' : ActorMethod<[], Array<[string, DesignMapping]>>,
  'getDesignMapping' : ActorMethod<[string], [] | [DesignMapping]>,
  'getFilteredOutKarigars' : ActorMethod<[], Array<string>>,
  'getKarigars' : ActorMethod<[], Array<Karigar>>,
  'getMasterDesignExcel' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMasterDesigns' : ActorMethod<[], Array<string>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrderStatusLog' : ActorMethod<[string], Array<OrderStatusLog>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getReadyOrders' : ActorMethod<[], Array<Order>>,
  'getUniqueKarigarsFromDesignMappings' : ActorMethod<[], Array<string>>,
  'getUser' : ActorMethod<[string], [] | [AppUser]>,
  'getUserByLoginId' : ActorMethod<[string], [] | [AppUser]>,
  'initDefaultAdmin' : ActorMethod<[], undefined>,
  'isExistingDesignCodes' : ActorMethod<[string], boolean>,
  'listUsers' : ActorMethod<[], Array<AppUser>>,
  'logOrderStatusChange' : ActorMethod<
    [string, OrderStatus, OrderStatus, string],
    undefined
  >,
  'login' : ActorMethod<
    [string, string],
    [] | [
      {
        'id' : string,
        'name' : string,
        'role' : AppRole,
        'karigarName' : [] | [string],
      }
    ]
  >,
  'markOrdersAsPending' : ActorMethod<[Array<string>, string], undefined>,
  'markOrdersAsReady' : ActorMethod<[Array<string>, string], undefined>,
  'persistMasterDataRows' : ActorMethod<
    [Array<MasterDataRow>],
    MasterPersistedResponse
  >,
  'reconcileMasterFile' : ActorMethod<[], MasterReconciliationResult>,
  'registerKarigar' : ActorMethod<[string], undefined>,
  'resetActiveOrders' : ActorMethod<[], undefined>,
  'resetDefaultAdmin' : ActorMethod<[], undefined>,
  'resetUserPassword' : ActorMethod<[string, string], undefined>,
  'saveDesignMapping' : ActorMethod<[DesignMapping], undefined>,
  'supplyAndReturnOrder' : ActorMethod<[string, bigint, string], undefined>,
  'supplyOrder' : ActorMethod<[string, bigint, string], undefined>,
  'updateMasterDesignKarigars' : ActorMethod<[string, bigint], undefined>,
  'updateOrderQuantity' : ActorMethod<[string, bigint, string], undefined>,
  'updateUser' : ActorMethod<
    [string, string, string, AppRole, [] | [string], AppStatus],
    undefined
  >,
  'uploadDesignImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadMasterDesignExcel' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];