/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DesignMapping {
  'createdAt' : Time,
  'createdBy' : Principal,
  'karigarName' : string,
  'updatedAt' : Time,
  'updatedBy' : [] | [Principal],
  'genericName' : string,
  'designCode' : string,
}
export type ExternalBlob = Uint8Array;
export interface Karigar {
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export interface Order {
  'weight' : number,
  'status' : OrderStatus,
  'createdAt' : Time,
  'size' : number,
  'orderType' : OrderType,
  'design' : string,
  'orderId' : string,
  'orderNo' : string,
  'karigarName' : string,
  'updatedAt' : Time,
  'genericName' : string,
  'quantity' : bigint,
  'remarks' : string,
  'product' : string,
}
export type OrderStatus = { 'Ready' : null } |
  { 'Hallmark' : null } |
  { 'ReturnFromHallmark' : null } |
  { 'Pending' : null };
export type OrderType = { 'CO' : null } |
  { 'RB' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKarigar' : ActorMethod<[string], undefined>,
  'batchUploadDesignImages' : ActorMethod<
    [Array<[string, ExternalBlob]>],
    undefined
  >,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'getDesignImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getDesignMapping' : ActorMethod<[string], DesignMapping>,
  'getKarigars' : ActorMethod<[], Array<Karigar>>,
  'getOrders' : ActorMethod<
    [[] | [OrderStatus], [] | [OrderType], [] | [string]],
    Array<Order>
  >,
  'reassignDesign' : ActorMethod<[string, string], undefined>,
  'saveDesignMapping' : ActorMethod<[string, string, string], undefined>,
  'saveOrder' : ActorMethod<
    [
      string,
      OrderType,
      string,
      string,
      number,
      number,
      bigint,
      string,
      string,
      string,
      OrderStatus,
      string,
    ],
    undefined
  >,
  'uploadDesignImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];