/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MappingRecord = IDL.Record({
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const Time = IDL.Int;
export const DesignMapping = IDL.Record({
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'karigarName' : IDL.Text,
  'updatedAt' : Time,
  'updatedBy' : IDL.Opt(IDL.Principal),
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Karigar = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
});
export const OrderStatus = IDL.Variant({
  'Ready' : IDL.Null,
  'Hallmark' : IDL.Null,
  'ReturnFromHallmark' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderType = IDL.Variant({ 'CO' : IDL.Null, 'RB' : IDL.Null });
export const Order = IDL.Record({
  'weight' : IDL.Float64,
  'status' : OrderStatus,
  'createdAt' : Time,
  'size' : IDL.Float64,
  'orderType' : OrderType,
  'design' : IDL.Text,
  'orderId' : IDL.Text,
  'orderNo' : IDL.Text,
  'karigarName' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'genericName' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'remarks' : IDL.Text,
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addKarigar' : IDL.Func([IDL.Text], [], []),
  'assignOrdersToKarigar' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
  'batchSaveDesignMappings' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
      [],
      [],
    ),
  'batchUploadDesignImages' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      [],
      [],
    ),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'getAllMasterDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
      ['query'],
    ),
  'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getDesignMapping' : IDL.Func([IDL.Text], [DesignMapping], ['query']),
  'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
  'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMasterDesignKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrders' : IDL.Func(
      [IDL.Opt(OrderStatus), IDL.Opt(OrderType), IDL.Opt(IDL.Text)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersWithMappings' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUniqueKarigarsFromDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'isExistingDesignCodes' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  'reassignDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveOrder' : IDL.Func(
      [
        IDL.Text,
        OrderType,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateMasterDesignKarigars' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateOrdersStatusToReady' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadDesignMapping' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
  'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MappingRecord = IDL.Record({
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const Time = IDL.Int;
  const DesignMapping = IDL.Record({
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'karigarName' : IDL.Text,
    'updatedAt' : Time,
    'updatedBy' : IDL.Opt(IDL.Principal),
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Karigar = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
  });
  const OrderStatus = IDL.Variant({
    'Ready' : IDL.Null,
    'Hallmark' : IDL.Null,
    'ReturnFromHallmark' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'CO' : IDL.Null, 'RB' : IDL.Null });
  const Order = IDL.Record({
    'weight' : IDL.Float64,
    'status' : OrderStatus,
    'createdAt' : Time,
    'size' : IDL.Float64,
    'orderType' : OrderType,
    'design' : IDL.Text,
    'orderId' : IDL.Text,
    'orderNo' : IDL.Text,
    'karigarName' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'genericName' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'remarks' : IDL.Text,
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addKarigar' : IDL.Func([IDL.Text], [], []),
    'assignOrdersToKarigar' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
    'batchSaveDesignMappings' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
        [],
        [],
      ),
    'batchUploadDesignImages' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        [],
        [],
      ),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'getAllMasterDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
        ['query'],
      ),
    'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getDesignMapping' : IDL.Func([IDL.Text], [DesignMapping], ['query']),
    'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
    'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMasterDesignKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrders' : IDL.Func(
        [IDL.Opt(OrderStatus), IDL.Opt(OrderType), IDL.Opt(IDL.Text)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersWithMappings' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUniqueKarigarsFromDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'isExistingDesignCodes' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    'reassignDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveOrder' : IDL.Func(
        [
          IDL.Text,
          OrderType,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateMasterDesignKarigars' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateOrdersStatusToReady' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadDesignMapping' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
    'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };