/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DesignMapping {
  'createdAt' : Time,
  'createdBy' : string,
  'karigarName' : string,
  'updatedAt' : Time,
  'updatedBy' : [] | [string],
  'genericName' : string,
  'designCode' : string,
}
export type ExternalBlob = Uint8Array;
export interface Karigar {
  'name' : string,
  'createdAt' : Time,
  'createdBy' : string,
}
export interface MappingRecord {
  'karigarName' : string,
  'genericName' : string,
  'designCode' : string,
}
export interface MasterDataRow {
  'weight' : number,
  'karigar' : string,
  'orderDate' : [] | [Time],
  'orderNo' : string,
  'quantity' : bigint,
  'designCode' : string,
}
export interface MasterPersistedResponse { 'persisted' : Array<Order> }
export interface MasterReconciliationResult {
  'missingInMasterCount' : bigint,
  'newLinesCount' : bigint,
  'alreadyExistingRows' : bigint,
  'totalUploadedRows' : bigint,
  'newLines' : Array<MasterDataRow>,
  'missingInMaster' : Array<Order>,
}
export interface Order {
  'weight' : number,
  'status' : OrderStatus,
  'readyDate' : [] | [Time],
  'originalOrderId' : [] | [string],
  'createdAt' : Time,
  'size' : number,
  'orderDate' : [] | [Time],
  'orderType' : OrderType,
  'design' : string,
  'orderId' : string,
  'orderNo' : string,
  'karigarName' : [] | [string],
  'updatedAt' : Time,
  'genericName' : [] | [string],
  'quantity' : bigint,
  'remarks' : string,
  'product' : string,
}
export type OrderStatus = { 'Ready' : null } |
  { 'Hallmark' : null } |
  { 'ReturnFromHallmark' : null } |
  { 'Pending' : null };
export type OrderType = { 'CO' : null } |
  { 'RB' : null } |
  { 'SO' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKarigar' : ActorMethod<[string], undefined>,
  'assignOrdersToKarigar' : ActorMethod<[Array<MappingRecord>], undefined>,
  'batchDeleteOrders' : ActorMethod<[Array<string>], undefined>,
  'batchGetByStatus' : ActorMethod<[Array<string>, OrderStatus], Array<string>>,
  'batchReturnOrdersToPending' : ActorMethod<
    [Array<[string, bigint]>],
    undefined
  >,
  'batchSaveDesignMappings' : ActorMethod<
    [Array<[string, DesignMapping]>],
    undefined
  >,
  'batchSupplyNewRBOrders' : ActorMethod<[Array<[string, bigint]>], undefined>,
  'batchSupplyRBOrders' : ActorMethod<[Array<[string, bigint]>], undefined>,
  'batchUpdateOrderStatus' : ActorMethod<
    [Array<string>, OrderStatus],
    undefined
  >,
  'batchUploadDesignImages' : ActorMethod<
    [Array<[string, ExternalBlob]>],
    undefined
  >,
  'clearAllDesignMappings' : ActorMethod<[], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deleteReadyOrder' : ActorMethod<[string], undefined>,
  'getAllMasterDesignMappings' : ActorMethod<
    [],
    Array<[string, DesignMapping]>
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getDesignCountByKarigar' : ActorMethod<[string], [] | [bigint]>,
  'getDesignImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getDesignImageMapping' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getDesignMapping' : ActorMethod<[string], DesignMapping>,
  'getKarigars' : ActorMethod<[], Array<Karigar>>,
  'getMasterDesignExcel' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMasterDesignKarigars' : ActorMethod<[], Array<string>>,
  'getMasterDesigns' : ActorMethod<[], Array<[string, string, string]>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<
    [[] | [OrderStatus], [] | [OrderType], [] | [string]],
    Array<Order>
  >,
  'getOrdersWithMappings' : ActorMethod<[], Array<Order>>,
  'getReadyOrders' : ActorMethod<[], Array<Order>>,
  'getReadyOrdersByDateRange' : ActorMethod<[Time, Time], Array<Order>>,
  'getUniqueKarigarsFromDesignMappings' : ActorMethod<[], Array<string>>,
  'getUnreturnedOrders' : ActorMethod<[], Array<Order>>,
  'isExistingDesignCodes' : ActorMethod<[Array<string>], Array<boolean>>,
  'markAllAsReady' : ActorMethod<[], undefined>,
  'markOrdersAsReady' : ActorMethod<[Array<string>], undefined>,
  'persistMasterDataRows' : ActorMethod<
    [Array<MasterDataRow>],
    MasterPersistedResponse
  >,
  'reassignDesign' : ActorMethod<[string, string], undefined>,
  'reconcileMasterFile' : ActorMethod<
    [Array<MasterDataRow>],
    MasterReconciliationResult
  >,
  'resetActiveOrders' : ActorMethod<[], undefined>,
  'returnOrdersToPending' : ActorMethod<[string, bigint], undefined>,
  'returnReadyOrderToPending' : ActorMethod<[string, bigint], undefined>,
  'saveDesignMapping' : ActorMethod<[string, string, string], undefined>,
  'saveOrder' : ActorMethod<
    [
      string,
      OrderType,
      string,
      string,
      number,
      number,
      bigint,
      string,
      string,
      [] | [Time],
    ],
    undefined
  >,
  'supplyAndReturnOrder' : ActorMethod<[string, bigint], undefined>,
  'supplyOrder' : ActorMethod<[string, bigint], undefined>,
  'updateDesignGroupStatus' : ActorMethod<[Array<string>], undefined>,
  'updateDesignMapping' : ActorMethod<[string, string, string], undefined>,
  'updateMasterDesignKarigars' : ActorMethod<[Array<string>], undefined>,
  'uploadDesignImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadDesignMapping' : ActorMethod<[Array<MappingRecord>], undefined>,
  'uploadMasterDesignExcel' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];