/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MappingRecord = IDL.Record({
  'karigarName' : IDL.Text,
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Ready' : IDL.Null,
  'Hallmark' : IDL.Null,
  'ReturnFromHallmark' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const DesignMapping = IDL.Record({
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'karigarName' : IDL.Text,
  'updatedAt' : Time,
  'updatedBy' : IDL.Opt(IDL.Text),
  'genericName' : IDL.Text,
  'designCode' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OrderType = IDL.Variant({
  'CO' : IDL.Null,
  'RB' : IDL.Null,
  'SO' : IDL.Null,
});
export const Order = IDL.Record({
  'weight' : IDL.Float64,
  'status' : OrderStatus,
  'readyDate' : IDL.Opt(Time),
  'originalOrderId' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'size' : IDL.Float64,
  'orderDate' : IDL.Opt(Time),
  'orderType' : OrderType,
  'design' : IDL.Text,
  'orderId' : IDL.Text,
  'orderNo' : IDL.Text,
  'karigarName' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'genericName' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'remarks' : IDL.Text,
  'product' : IDL.Text,
});
export const Karigar = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
});
export const MasterDataRow = IDL.Record({
  'weight' : IDL.Float64,
  'karigar' : IDL.Text,
  'orderDate' : IDL.Opt(Time),
  'orderNo' : IDL.Text,
  'quantity' : IDL.Nat,
  'designCode' : IDL.Text,
});
export const MasterPersistedResponse = IDL.Record({
  'persisted' : IDL.Vec(Order),
});
export const MasterReconciliationResult = IDL.Record({
  'missingInMasterCount' : IDL.Nat,
  'newLinesCount' : IDL.Nat,
  'alreadyExistingRows' : IDL.Nat,
  'totalUploadedRows' : IDL.Nat,
  'newLines' : IDL.Vec(MasterDataRow),
  'missingInMaster' : IDL.Vec(Order),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addKarigar' : IDL.Func([IDL.Text], [], []),
  'assignOrdersToKarigar' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
  'batchDeleteOrders' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'batchGetByStatus' : IDL.Func(
      [IDL.Vec(IDL.Text), OrderStatus],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'batchReturnOrdersToPending' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'batchSaveDesignMappings' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
      [],
      [],
    ),
  'batchSupplyNewRBOrders' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'batchSupplyRBOrders' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'batchUpdateOrderStatus' : IDL.Func([IDL.Vec(IDL.Text), OrderStatus], [], []),
  'batchUploadDesignImages' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      [],
      [],
    ),
  'clearAllDesignMappings' : IDL.Func([], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deleteReadyOrder' : IDL.Func([IDL.Text], [], []),
  'getAllMasterDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getDesignCountByKarigar' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getDesignImageMapping' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getDesignMapping' : IDL.Func([IDL.Text], [DesignMapping], ['query']),
  'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
  'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMasterDesignKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMasterDesigns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func(
      [IDL.Opt(OrderStatus), IDL.Opt(OrderType), IDL.Opt(IDL.Text)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersWithMappings' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getReadyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getReadyOrdersByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUniqueKarigarsFromDesignMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUnreturnedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'isExistingDesignCodes' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  'markAllAsReady' : IDL.Func([], [], []),
  'markOrdersAsReady' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'persistMasterDataRows' : IDL.Func(
      [IDL.Vec(MasterDataRow)],
      [MasterPersistedResponse],
      [],
    ),
  'reassignDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reconcileMasterFile' : IDL.Func(
      [IDL.Vec(MasterDataRow)],
      [MasterReconciliationResult],
      [],
    ),
  'resetActiveOrders' : IDL.Func([], [], []),
  'returnOrdersToPending' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'returnReadyOrderToPending' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveOrder' : IDL.Func(
      [
        IDL.Text,
        OrderType,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
  'supplyAndReturnOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'supplyOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateDesignGroupStatus' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMasterDesignKarigars' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadDesignMapping' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
  'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MappingRecord = IDL.Record({
    'karigarName' : IDL.Text,
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Ready' : IDL.Null,
    'Hallmark' : IDL.Null,
    'ReturnFromHallmark' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const DesignMapping = IDL.Record({
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'karigarName' : IDL.Text,
    'updatedAt' : Time,
    'updatedBy' : IDL.Opt(IDL.Text),
    'genericName' : IDL.Text,
    'designCode' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OrderType = IDL.Variant({
    'CO' : IDL.Null,
    'RB' : IDL.Null,
    'SO' : IDL.Null,
  });
  const Order = IDL.Record({
    'weight' : IDL.Float64,
    'status' : OrderStatus,
    'readyDate' : IDL.Opt(Time),
    'originalOrderId' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'size' : IDL.Float64,
    'orderDate' : IDL.Opt(Time),
    'orderType' : OrderType,
    'design' : IDL.Text,
    'orderId' : IDL.Text,
    'orderNo' : IDL.Text,
    'karigarName' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'genericName' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'remarks' : IDL.Text,
    'product' : IDL.Text,
  });
  const Karigar = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
  });
  const MasterDataRow = IDL.Record({
    'weight' : IDL.Float64,
    'karigar' : IDL.Text,
    'orderDate' : IDL.Opt(Time),
    'orderNo' : IDL.Text,
    'quantity' : IDL.Nat,
    'designCode' : IDL.Text,
  });
  const MasterPersistedResponse = IDL.Record({ 'persisted' : IDL.Vec(Order) });
  const MasterReconciliationResult = IDL.Record({
    'missingInMasterCount' : IDL.Nat,
    'newLinesCount' : IDL.Nat,
    'alreadyExistingRows' : IDL.Nat,
    'totalUploadedRows' : IDL.Nat,
    'newLines' : IDL.Vec(MasterDataRow),
    'missingInMaster' : IDL.Vec(Order),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addKarigar' : IDL.Func([IDL.Text], [], []),
    'assignOrdersToKarigar' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
    'batchDeleteOrders' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'batchGetByStatus' : IDL.Func(
        [IDL.Vec(IDL.Text), OrderStatus],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'batchReturnOrdersToPending' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'batchSaveDesignMappings' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
        [],
        [],
      ),
    'batchSupplyNewRBOrders' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'batchSupplyRBOrders' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'batchUpdateOrderStatus' : IDL.Func(
        [IDL.Vec(IDL.Text), OrderStatus],
        [],
        [],
      ),
    'batchUploadDesignImages' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        [],
        [],
      ),
    'clearAllDesignMappings' : IDL.Func([], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deleteReadyOrder' : IDL.Func([IDL.Text], [], []),
    'getAllMasterDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DesignMapping))],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getDesignCountByKarigar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getDesignImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getDesignImageMapping' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getDesignMapping' : IDL.Func([IDL.Text], [DesignMapping], ['query']),
    'getKarigars' : IDL.Func([], [IDL.Vec(Karigar)], ['query']),
    'getMasterDesignExcel' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMasterDesignKarigars' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMasterDesigns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func(
        [IDL.Opt(OrderStatus), IDL.Opt(OrderType), IDL.Opt(IDL.Text)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersWithMappings' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getReadyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getReadyOrdersByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUniqueKarigarsFromDesignMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUnreturnedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'isExistingDesignCodes' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    'markAllAsReady' : IDL.Func([], [], []),
    'markOrdersAsReady' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'persistMasterDataRows' : IDL.Func(
        [IDL.Vec(MasterDataRow)],
        [MasterPersistedResponse],
        [],
      ),
    'reassignDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reconcileMasterFile' : IDL.Func(
        [IDL.Vec(MasterDataRow)],
        [MasterReconciliationResult],
        [],
      ),
    'resetActiveOrders' : IDL.Func([], [], []),
    'returnOrdersToPending' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'returnReadyOrderToPending' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveOrder' : IDL.Func(
        [
          IDL.Text,
          OrderType,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
    'supplyAndReturnOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'supplyOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateDesignGroupStatus' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateDesignMapping' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMasterDesignKarigars' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'uploadDesignImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadDesignMapping' : IDL.Func([IDL.Vec(MappingRecord)], [], []),
    'uploadMasterDesignExcel' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };