/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MappingRecord {
    karigarName: string;
    excelGenericName: string;
    genericName: string;
    designCode: string;
}
export interface MasterDataRow {
    karigar: string;
    genericName: string;
    designCode: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderStatusLog {
    id: string;
    oldStatus: OrderStatus;
    orderId: string;
    updatedAt: Time;
    updatedBy: string;
    newStatus: OrderStatus;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Karigar {
    name: string;
    createdAt: Time;
    createdBy: string;
}
export interface Order {
    weight: number;
    status: OrderStatus;
    readyDate?: Time;
    originalOrderId?: string;
    createdAt: Time;
    movedBy?: string;
    size: number;
    orderDate?: Time;
    orderType: OrderType;
    design: string;
    orderId: string;
    orderNo: string;
    karigarName?: string;
    updatedAt: Time;
    updatedBy?: string;
    genericName?: string;
    quantity: bigint;
    lastAction?: string;
    remarks: string;
    product: string;
}
export interface AppUser {
    id: string;
    status: AppStatus;
    name: string;
    createdAt: Time;
    role: AppRole;
    karigarName?: string;
    loginId: string;
    passwordHash: string;
}
export interface MasterDesignMapping {
    karigar: string;
    excelGenericName: string;
    genericName: string;
    designCode: string;
}
export interface DesignMapping {
    createdAt: Time;
    createdBy: string;
    karigarName: string;
    updatedAt: Time;
    updatedBy?: string;
    genericName: string;
    designCode: string;
}
export interface MasterPersistedResponse {
    reconciliationResult: MasterReconciliationResult;
    persistedRows: Array<MasterDataRow>;
}
export interface MasterReconciliationResult {
    missingInExcel: Array<MasterDataRow>;
    matchedRows: Array<MasterDataRow>;
    missingInSystem: Array<MasterDataRow>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppRole {
    Staff = "Staff",
    Admin = "Admin",
    Karigar = "Karigar"
}
export enum AppStatus {
    Inactive = "Inactive",
    Active = "Active"
}
export enum OrderStatus {
    Ready = "Ready",
    Hallmark = "Hallmark",
    ReturnFromHallmark = "ReturnFromHallmark",
    Pending = "Pending"
}
export enum OrderType {
    CO = "CO",
    RB = "RB",
    SO = "SO"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    batchSaveDesignMappings(mappings: Array<MappingRecord>, createdBy: string): Promise<void>;
    batchUpdateOrderStatus(orderIds: Array<string>, newStatus: OrderStatus, updatedBy: string): Promise<void>;
    clearAllDesignMappings(): Promise<void>;
    createOrder(orderNo: string, orderType: OrderType, product: string, design: string, weight: number, size: number, quantity: bigint, remarks: string, genericName: string | null, karigarName: string | null): Promise<string>;
    createOrderWithDate(orderNo: string, orderType: OrderType, product: string, design: string, weight: number, size: number, quantity: bigint, remarks: string, genericName: string | null, karigarName: string | null, orderDate: Time | null): Promise<string>;
    createUser(name: string, loginId: string, passwordHash: string, role: AppRole, karigarName: string | null): Promise<string>;
    deleteOrder(orderId: string): Promise<void>;
    getAllMasterDesignMappings(): Promise<Array<MasterDesignMapping>>;
    getAllOrderStatusLogs(): Promise<Array<OrderStatusLog>>;
    getAllOrders(): Promise<Array<Order>>;
    getDesignCountByKarigar(): Promise<Array<[string, bigint]>>;
    getDesignImage(designCode: string): Promise<ExternalBlob | null>;
    getDesignImageMapping(): Promise<Array<[string, DesignMapping]>>;
    getDesignMapping(designCode: string): Promise<DesignMapping | null>;
    getFilteredOutKarigars(): Promise<Array<string>>;
    getKarigars(): Promise<Array<Karigar>>;
    getMasterDesignExcel(): Promise<ExternalBlob | null>;
    getMasterDesigns(): Promise<Array<string>>;
    getOrder(orderId: string): Promise<Order | null>;
    getOrderStatusLog(orderId: string): Promise<Array<OrderStatusLog>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getReadyOrders(): Promise<Array<Order>>;
    getUniqueKarigarsFromDesignMappings(): Promise<Array<string>>;
    getUser(id: string): Promise<AppUser | null>;
    getUserByLoginId(loginId: string): Promise<AppUser | null>;
    initDefaultAdmin(): Promise<void>;
    isExistingDesignCodes(designCode: string): Promise<boolean>;
    listUsers(): Promise<Array<AppUser>>;
    logOrderStatusChange(orderId: string, oldStatus: OrderStatus, newStatus: OrderStatus, updatedBy: string): Promise<void>;
    login(loginId: string, hashedPassword: string): Promise<{
        id: string;
        name: string;
        role: AppRole;
        karigarName?: string;
    } | null>;
    markOrdersAsPending(orderIds: Array<string>, updatedBy: string): Promise<void>;
    markOrdersAsReady(orderIds: Array<string>, updatedBy: string): Promise<void>;
    persistMasterDataRows(rows: Array<MasterDataRow>): Promise<MasterPersistedResponse>;
    reconcileMasterFile(): Promise<MasterReconciliationResult>;
    registerKarigar(name: string): Promise<void>;
    resetActiveOrders(): Promise<void>;
    resetDefaultAdmin(): Promise<void>;
    resetUserPassword(id: string, newPasswordHash: string): Promise<void>;
    saveDesignMapping(designMapping: DesignMapping): Promise<void>;
    supplyAndReturnOrder(orderId: string, suppliedQuantity: bigint, updatedBy: string): Promise<void>;
    supplyOrder(orderId: string, suppliedQuantity: bigint, updatedBy: string): Promise<void>;
    updateMasterDesignKarigars(designCode: string, count: bigint): Promise<void>;
    updateOrderQuantity(orderId: string, newQuantity: bigint, updatedBy: string): Promise<void>;
    updateUser(id: string, name: string, loginId: string, role: AppRole, karigarName: string | null, status: AppStatus): Promise<void>;
    uploadDesignImage(designCode: string, image: ExternalBlob): Promise<void>;
    uploadMasterDesignExcel(excelFile: ExternalBlob): Promise<void>;
}
import type { AppRole as _AppRole, AppStatus as _AppStatus, AppUser as _AppUser, DesignMapping as _DesignMapping, ExternalBlob as _ExternalBlob, Order as _Order, OrderStatus as _OrderStatus, OrderStatusLog as _OrderStatusLog, OrderType as _OrderType, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async batchSaveDesignMappings(arg0: Array<MappingRecord>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSaveDesignMappings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSaveDesignMappings(arg0, arg1);
            return result;
        }
    }
    async batchUpdateOrderStatus(arg0: Array<string>, arg1: OrderStatus, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpdateOrderStatus(arg0, to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpdateOrderStatus(arg0, to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async clearAllDesignMappings(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllDesignMappings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllDesignMappings();
            return result;
        }
    }
    async createOrder(arg0: string, arg1: OrderType, arg2: string, arg3: string, arg4: number, arg5: number, arg6: bigint, arg7: string, arg8: string | null, arg9: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_OrderType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_OrderType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async createOrderWithDate(arg0: string, arg1: OrderType, arg2: string, arg3: string, arg4: number, arg5: number, arg6: bigint, arg7: string, arg8: string | null, arg9: string | null, arg10: Time | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrderWithDate(arg0, to_candid_OrderType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrderWithDate(arg0, to_candid_OrderType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: AppRole, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_AppRole_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_AppRole_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async getAllMasterDesignMappings(): Promise<Array<MasterDesignMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMasterDesignMappings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMasterDesignMappings();
            return result;
        }
    }
    async getAllOrderStatusLogs(): Promise<Array<OrderStatusLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrderStatusLogs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrderStatusLogs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignCountByKarigar(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignCountByKarigar();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignCountByKarigar();
            return result;
        }
    }
    async getDesignImage(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignImage(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignImage(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignImageMapping(): Promise<Array<[string, DesignMapping]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignImageMapping();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignImageMapping();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesignMapping(arg0: string): Promise<DesignMapping | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignMapping(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignMapping(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredOutKarigars(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredOutKarigars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredOutKarigars();
            return result;
        }
    }
    async getKarigars(): Promise<Array<Karigar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKarigars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKarigars();
            return result;
        }
    }
    async getMasterDesignExcel(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterDesignExcel();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterDesignExcel();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMasterDesigns(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMasterDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMasterDesigns();
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStatusLog(arg0: string): Promise<Array<OrderStatusLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatusLog(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatusLog(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReadyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadyOrders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadyOrders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUniqueKarigarsFromDesignMappings(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueKarigarsFromDesignMappings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueKarigarsFromDesignMappings();
            return result;
        }
    }
    async getUser(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByLoginId(arg0: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByLoginId(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByLoginId(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async initDefaultAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initDefaultAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initDefaultAdmin();
            return result;
        }
    }
    async isExistingDesignCodes(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isExistingDesignCodes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isExistingDesignCodes(arg0);
            return result;
        }
    }
    async listUsers(): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async logOrderStatusChange(arg0: string, arg1: OrderStatus, arg2: OrderStatus, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logOrderStatusChange(arg0, to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg1), to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logOrderStatusChange(arg0, to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg1), to_candid_OrderStatus_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        id: string;
        name: string;
        role: AppRole;
        karigarName?: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async markOrdersAsPending(arg0: Array<string>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrdersAsPending(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrdersAsPending(arg0, arg1);
            return result;
        }
    }
    async markOrdersAsReady(arg0: Array<string>, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrdersAsReady(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrdersAsReady(arg0, arg1);
            return result;
        }
    }
    async persistMasterDataRows(arg0: Array<MasterDataRow>): Promise<MasterPersistedResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.persistMasterDataRows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.persistMasterDataRows(arg0);
            return result;
        }
    }
    async reconcileMasterFile(): Promise<MasterReconciliationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.reconcileMasterFile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reconcileMasterFile();
            return result;
        }
    }
    async registerKarigar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerKarigar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerKarigar(arg0);
            return result;
        }
    }
    async resetActiveOrders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetActiveOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetActiveOrders();
            return result;
        }
    }
    async resetDefaultAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetDefaultAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetDefaultAdmin();
            return result;
        }
    }
    async resetUserPassword(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPassword(arg0, arg1);
            return result;
        }
    }
    async saveDesignMapping(arg0: DesignMapping): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesignMapping(to_candid_DesignMapping_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesignMapping(to_candid_DesignMapping_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async supplyAndReturnOrder(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supplyAndReturnOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supplyAndReturnOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async supplyOrder(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supplyOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supplyOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMasterDesignKarigars(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMasterDesignKarigars(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMasterDesignKarigars(arg0, arg1);
            return result;
        }
    }
    async updateOrderQuantity(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderQuantity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderQuantity(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: AppRole, arg4: string | null, arg5: AppStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_AppRole_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_AppStatus_n48(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_AppRole_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_AppStatus_n48(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async uploadDesignImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDesignImage(arg0, await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDesignImage(arg0, await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadMasterDesignExcel(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMasterDesignExcel(await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMasterDesignExcel(await to_candid_ExternalBlob_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_AppStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppStatus): AppStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_AppUser_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUser): AppUser {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_DesignMapping_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignMapping): DesignMapping {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatusLog_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatusLog): OrderStatusLog {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DesignMapping]): DesignMapping | null {
    return value.length === 0 ? null : from_candid_DesignMapping_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUser]): AppUser | null {
    return value.length === 0 ? null : from_candid_AppUser_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        id: string;
        name: string;
        role: _AppRole;
        karigarName: [] | [string];
    }]): {
    id: string;
    name: string;
    role: AppRole;
    karigarName?: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    oldStatus: _OrderStatus;
    orderId: string;
    updatedAt: _Time;
    updatedBy: string;
    newStatus: _OrderStatus;
}): {
    id: string;
    oldStatus: OrderStatus;
    orderId: string;
    updatedAt: Time;
    updatedBy: string;
    newStatus: OrderStatus;
} {
    return {
        id: value.id,
        oldStatus: from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.oldStatus),
        orderId: value.orderId,
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy,
        newStatus: from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.newStatus)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    status: _OrderStatus;
    readyDate: [] | [_Time];
    originalOrderId: [] | [string];
    createdAt: _Time;
    movedBy: [] | [string];
    size: number;
    orderDate: [] | [_Time];
    orderType: _OrderType;
    design: string;
    orderId: string;
    orderNo: string;
    karigarName: [] | [string];
    updatedAt: _Time;
    updatedBy: [] | [string];
    genericName: [] | [string];
    quantity: bigint;
    lastAction: [] | [string];
    remarks: string;
    product: string;
}): {
    weight: number;
    status: OrderStatus;
    readyDate?: Time;
    originalOrderId?: string;
    createdAt: Time;
    movedBy?: string;
    size: number;
    orderDate?: Time;
    orderType: OrderType;
    design: string;
    orderId: string;
    orderNo: string;
    karigarName?: string;
    updatedAt: Time;
    updatedBy?: string;
    genericName?: string;
    quantity: bigint;
    lastAction?: string;
    remarks: string;
    product: string;
} {
    return {
        weight: value.weight,
        status: from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.status),
        readyDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.readyDate)),
        originalOrderId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.originalOrderId)),
        createdAt: value.createdAt,
        movedBy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.movedBy)),
        size: value.size,
        orderDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.orderDate)),
        orderType: from_candid_OrderType_n26(_uploadFile, _downloadFile, value.orderType),
        design: value.design,
        orderId: value.orderId,
        orderNo: value.orderNo,
        karigarName: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.karigarName)),
        updatedAt: value.updatedAt,
        updatedBy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.updatedBy)),
        genericName: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.genericName)),
        quantity: value.quantity,
        lastAction: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.lastAction)),
        remarks: value.remarks,
        product: value.product
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    createdBy: string;
    karigarName: string;
    updatedAt: _Time;
    updatedBy: [] | [string];
    genericName: string;
    designCode: string;
}): {
    createdAt: Time;
    createdBy: string;
    karigarName: string;
    updatedAt: Time;
    updatedBy?: string;
    genericName: string;
    designCode: string;
} {
    return {
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        karigarName: value.karigarName,
        updatedAt: value.updatedAt,
        updatedBy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.updatedBy)),
        genericName: value.genericName,
        designCode: value.designCode
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppStatus;
    name: string;
    createdAt: _Time;
    role: _AppRole;
    karigarName: [] | [string];
    loginId: string;
    passwordHash: string;
}): {
    id: string;
    status: AppStatus;
    name: string;
    createdAt: Time;
    role: AppRole;
    karigarName?: string;
    loginId: string;
    passwordHash: string;
} {
    return {
        id: value.id,
        status: from_candid_AppStatus_n39(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_AppRole_n41(_uploadFile, _downloadFile, value.role),
        karigarName: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.karigarName)),
        loginId: value.loginId,
        passwordHash: value.passwordHash
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: _AppRole;
    karigarName: [] | [string];
}): {
    id: string;
    name: string;
    role: AppRole;
    karigarName?: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_AppRole_n41(_uploadFile, _downloadFile, value.role),
        karigarName: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.karigarName))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _DesignMapping]): [string, DesignMapping] {
    return [
        value[0],
        from_candid_DesignMapping_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ready: null;
} | {
    Hallmark: null;
} | {
    ReturnFromHallmark: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Ready" in value ? OrderStatus.Ready : "Hallmark" in value ? OrderStatus.Hallmark : "ReturnFromHallmark" in value ? OrderStatus.ReturnFromHallmark : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CO: null;
} | {
    RB: null;
} | {
    SO: null;
}): OrderType {
    return "CO" in value ? OrderType.CO : "RB" in value ? OrderType.RB : "SO" in value ? OrderType.SO : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
}): AppStatus {
    return "Inactive" in value ? AppStatus.Inactive : "Active" in value ? AppStatus.Active : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Staff: null;
} | {
    Admin: null;
} | {
    Karigar: null;
}): AppRole {
    return "Staff" in value ? AppRole.Staff : "Admin" in value ? AppRole.Admin : "Karigar" in value ? AppRole.Karigar : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderStatusLog>): Array<OrderStatusLog> {
    return value.map((x)=>from_candid_OrderStatusLog_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _DesignMapping]>): Array<[string, DesignMapping]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppUser>): Array<AppUser> {
    return value.map((x)=>from_candid_AppUser_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_AppStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppStatus): _AppStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_DesignMapping_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignMapping): _DesignMapping {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: Time;
    createdBy: string;
    karigarName: string;
    updatedAt: Time;
    updatedBy?: string;
    genericName: string;
    designCode: string;
}): {
    createdAt: _Time;
    createdBy: string;
    karigarName: string;
    updatedAt: _Time;
    updatedBy: [] | [string];
    genericName: string;
    designCode: string;
} {
    return {
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        karigarName: value.karigarName,
        updatedAt: value.updatedAt,
        updatedBy: value.updatedBy ? candid_some(value.updatedBy) : candid_none(),
        genericName: value.genericName,
        designCode: value.designCode
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    CO: null;
} | {
    RB: null;
} | {
    SO: null;
} {
    return value == OrderType.CO ? {
        CO: null
    } : value == OrderType.RB ? {
        RB: null
    } : value == OrderType.SO ? {
        SO: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Staff: null;
} | {
    Admin: null;
} | {
    Karigar: null;
} {
    return value == AppRole.Staff ? {
        Staff: null
    } : value == AppRole.Admin ? {
        Admin: null
    } : value == AppRole.Karigar ? {
        Karigar: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppStatus): {
    Inactive: null;
} | {
    Active: null;
} {
    return value == AppStatus.Inactive ? {
        Inactive: null
    } : value == AppStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Ready: null;
} | {
    Hallmark: null;
} | {
    ReturnFromHallmark: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Hallmark ? {
        Hallmark: null
    } : value == OrderStatus.ReturnFromHallmark ? {
        ReturnFromHallmark: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
